// This file will be generated by following script in Jenkins:
// echo export const version = { buildId: '${BUILD_ID}', rv: '${GIT_COMMIT}' }; > ./cydc/ClientApp/src/environments/version.ts
export const version = { buildId: 'local-id', rv: 'local-rv' }; 
