// This file will be generated by following script in Jenkins:
// echo export const version = { job: '%JOB_NAME%', buildId: '%BUILD_ID%', rv: '%GIT_COMMIT%' }; > ./cydc/ClientApp/src/environments/version.ts
export const version = { job: 'local-job', buildId: 'local-id', rv: 'local-rv' }; 
