name: Build Container
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  workflow_dispatch:
    
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build code locally
        run: |
          cd cydc
          dotnet publish ./cydc.csproj -c Release --os linux --arch x64 /t:PublishContainer

      - name: Tag container and push to Docker Hub
        run: |
          docker tag cydc ${{ secrets.DOCKER_USERNAME }}/cydc:latest
          docker tag cydc ${{ secrets.DOCKER_USERNAME }}/cydc:r-${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/cydc:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cydc:r-${{ github.run_number }}