name: Build Container
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  workflow_dispatch:
    
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build code locally
        run: |
          dotnet build -c Release